[package]
name = "trtllm"
version = "0.2.1"
edition = "2021"

[dependencies]
tonic = "0.11.0"
prost = "0.12.1"
prost-types = "0.12.1"
anyhow = { version = "1.0.75", features = ["backtrace"] }

[build-dependencies]
anyhow = "1.0.75"
tonic-build = "0.11.0"
walkdir = "2.4.0"
